
    const CONFIG = {
        entites: [
    {
        "pays": "madagascar",
        "pole": "télécom",
        "entite": "yas madagascar",
        "ville": "antananarivo",
        "facebook": "YasMadagascar",
        "linkedin": "yas-madagascar",
        "instagram": "yas madagacar",
        "youtube": "yasmadagascar",
        "tiktok": "yas madagascar",
        "X": "yas Madagascar",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "télécom",
        "entite": "pulse",
        "ville": "Antananarivo",
        "facebook": "",
        "linkedin": "",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "télécom",
        "entite": "connectéo",
        "ville": "Antananarivo",
        "facebook": "100063899261650",
        "linkedin": "connecteo-madagascar",
        "instagram": "",
        "youtube": "connecteomadagascar9177",
        "tiktok": "connecteo madagascar",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "télécom",
        "entite": "yas business madagascar",
        "ville": "Antananarivo",
        "facebook": "",
        "linkedin": "yas-business-madagascar",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "Digibank & fintech",
        "entite": "Mvola",
        "ville": "Antananarivo",
        "facebook": "MvolaMobileMoney",
        "linkedin": "mvola-madagascar",
        "instagram": "mvola madagascar",
        "youtube": "mvolamadagacar",
        "tiktok": "mvola madagascar",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "energie",
        "entite": "jovena",
        "ville": "Antananarivo",
        "facebook": "JovenaSourcedEnergies",
        "linkedin": "jovenna",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "energie",
        "entite": "CGHV",
        "ville": "Antananarivo",
        "facebook": "CGHV.mg",
        "linkedin": "compangie-g%C3%A9n%C3%A9rale-d-hydro%C3%A9lectricit%C3%A9-de-volobe-cghv",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "service finance",
        "entite": "BNI Madagascar",
        "ville": "Antananarivo",
        "facebook": "bnimadagascar",
        "linkedin": "bnimadagascar",
        "instagram": "bni.mg",
        "youtube": "bnimadagascar6363",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "service finance",
        "entite": "KRED",
        "ville": "Antananarivo",
        "facebook": "kredmadagascar",
        "linkedin": "kred-madagascar",
        "instagram": "kredmadagascar",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "service finance",
        "entite": "VIA Assurance",
        "ville": "Antananarivo",
        "facebook": "",
        "linkedin": "viaassurance",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "service finance",
        "entite": "Sanko",
        "ville": "Antananarivo",
        "facebook": "",
        "linkedin": "sanko-africa",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "immobilier",
        "entite": "first immo",
        "ville": "Antananarivo",
        "facebook": "firstimmomada",
        "linkedin": "first-immo-axian-properties",
        "instagram": "firstimmo mada",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "innovation & autres",
        "entite": "Nexta",
        "ville": "Antananarivo",
        "facebook": "",
        "linkedin": "nexta-accelerator",
        "instagram": "nexta incubator",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "innovation & autres",
        "entite": "Axian University",
        "ville": "Antananarivo",
        "facebook": "",
        "linkedin": "axian-university",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "innovation & autres",
        "entite": "Fondation axian",
        "ville": "Antananarivo",
        "facebook": "FondationAxian",
        "linkedin": "fondation-axian",
        "instagram": "fondation axian",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "madagascar",
        "pole": "innovation & autres",
        "entite": "42 antananarivo",
        "ville": "Antananarivo",
        "facebook": "42Antananarivo",
        "linkedin": "ecole-42-antananarivo",
        "instagram": "42antananarivo",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "sénégal",
        "pole": "télécom",
        "entite": "yas Sénégal",
        "ville": "None",
        "facebook": "YasSenegal",
        "linkedin": "yas-senegal",
        "instagram": "yas senegal",
        "youtube": "YasSenegal",
        "tiktok": "yas senegal",
        "X": "YasSenegal",
        "actif": "true"
    },
    {
        "pays": "sénégal",
        "pole": "Digibank & fintech",
        "entite": "Mixx Sénégal",
        "ville": "None",
        "facebook": "mixxsn",
        "linkedin": "mixx-s%C3%A9n%C3%A9gal",
        "instagram": "mixxsenegal",
        "youtube": "",
        "tiktok": "mixx.senegal",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "sénégal",
        "pole": "énergie",
        "entite": "Eydon",
        "ville": "None",
        "facebook": "eydonpetroleum",
        "linkedin": "eydonsa",
        "instagram": "eydonpetroleum sn",
        "youtube": "",
        "tiktok": "",
        "X": "eydonpetroleum",
        "actif": "true"
    },
    {
        "pays": "Tanzanie",
        "pole": "télécom",
        "entite": "yas Tanzanie",
        "ville": "None",
        "facebook": "YasInTanzania",
        "linkedin": "yas-tanzania",
        "instagram": "yastanzania",
        "youtube": "Yas tanzania",
        "tiktok": "yas tanzania",
        "X": "YasTanzania",
        "actif": "true"
    },
    {
        "pays": "Tanzanie",
        "pole": "télécom",
        "entite": "yas business Tanzanie",
        "ville": "None",
        "facebook": "",
        "linkedin": "yas-business-tanzania",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "Tanzanie",
        "pole": "Digibank & fintech",
        "entite": "Mixx Tanzanie",
        "ville": "None",
        "facebook": "61578518121102",
        "linkedin": "mixx-tanzania",
        "instagram": "mixx.tz",
        "youtube": "Mixx Tanzania",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "Togo",
        "pole": "télécom",
        "entite": "yas Togo",
        "ville": "None",
        "facebook": "yasintogo",
        "linkedin": "yas togo",
        "instagram": "yas togo",
        "youtube": "yas tg",
        "tiktok": "yas togo",
        "X": "YasTogo",
        "actif": "true"
    },
    {
        "pays": "Togo",
        "pole": "télécom",
        "entite": "yas business Togo",
        "ville": "None",
        "facebook": "",
        "linkedin": "yas -business-togo",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "Togo",
        "pole": "Digibank & fintech",
        "entite": "Mixx Togo",
        "ville": "None",
        "facebook": "MixxTogo",
        "linkedin": "mixxtogo",
        "instagram": "mixx togo",
        "youtube": "MixxTogo",
        "tiktok": "mixx togo",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "Comores",
        "pole": "télécom",
        "entite": "yas comores",
        "ville": "None",
        "facebook": "Yascomores",
        "linkedin": "yas-comores",
        "instagram": "yas comores",
        "youtube": "yas comores",
        "tiktok": "yas comores",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "Comores",
        "pole": "télécom",
        "entite": "yas business Comores",
        "ville": "None",
        "facebook": "",
        "linkedin": "yas-business-comores",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "Comores",
        "pole": "Digibank & fintech",
        "entite": "Mvola Comores",
        "ville": "None",
        "facebook": "McolaComores",
        "linkedin": "",
        "instagram": "MvolaComores",
        "youtube": "",
        "tiktok": "mvola comores",
        "X": "mvolacomores",
        "actif": "true"
    },
    {
        "pays": "kenya",
        "pole": "télécom",
        "entite": "Wananchi Group",
        "ville": "None",
        "facebook": "",
        "linkedin": "wananchi-online",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "kenya",
        "pole": "télécom",
        "entite": "Wananchi Télécom Limited",
        "ville": "None",
        "facebook": "",
        "linkedin": "wananchi-telecom",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "kenya",
        "pole": "télécom",
        "entite": "Wananchi TV",
        "ville": "None",
        "facebook": "",
        "linkedin": "",
        "instagram": "",
        "youtube": "",
        "tiktok": "wananchiitv",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "télécom",
        "entite": "Silver Links",
        "ville": "None",
        "facebook": "",
        "linkedin": "silver-links-the-african-carrier",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "télécom",
        "entite": "ToA",
        "ville": "None",
        "facebook": "",
        "linkedin": "towerco-of-africa",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "télécom",
        "entite": "Stellarix",
        "ville": "None",
        "facebook": "STELLARIXAdrica",
        "linkedin": "stellar-ix",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "télécom",
        "entite": "axian télécom",
        "ville": "None",
        "facebook": "",
        "linkedin": "axian-telecom",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "AXIANTELECOM",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "corporate",
        "entite": "axian group",
        "ville": "None",
        "facebook": "axiangroup",
        "linkedin": "urn:li:organization:13258727",
        "instagram": "axiangroup",
        "youtube": "axiangroup",
        "tiktok": "axiangroup",
        "X": "AxianGroup",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "corporate",
        "entite": "axian energy",
        "ville": "None",
        "facebook": "",
        "linkedin": "axianenergy",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "energie",
        "entite": "WeLight",
        "ville": "None",
        "facebook": "WeLightAfrica",
        "linkedin": "welightafrica",
        "instagram": "welight africa",
        "youtube": "welightafrica6912",
        "tiktok": "",
        "X": "",
        "actif": "true"
    },
    {
        "pays": "pan-Africain",
        "pole": "énergie",
        "entite": "NEA",
        "ville": "None",
        "facebook": "",
        "linkedin": "",
        "instagram": "",
        "youtube": "",
        "tiktok": "",
        "X": "",
        "actif": "true"
    }
],

        tokens: {
            linkedin: "",
            youtube: "",
            X: "",
        }
    };
    